modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="waffles"
version="1.0.0"
displayName="Waffles"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Daniel, MCreator"

[[dependencies.waffles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




